//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTramasMicros.LogMicros {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnviarLog.Trama", Namespace="http://schemas.datacontract.org/2004/07/ServicioMicros")]
    [System.SerializableAttribute()]
    public partial class EnviarLogTrama : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ltsDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ltsImpuestosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ltsMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ltsPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ltsServicesChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ltsTenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreArchivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ltsDiscount {
            get {
                return this.ltsDiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.ltsDiscountField, value) != true)) {
                    this.ltsDiscountField = value;
                    this.RaisePropertyChanged("ltsDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ltsImpuestos {
            get {
                return this.ltsImpuestosField;
            }
            set {
                if ((object.ReferenceEquals(this.ltsImpuestosField, value) != true)) {
                    this.ltsImpuestosField = value;
                    this.RaisePropertyChanged("ltsImpuestos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ltsMenu {
            get {
                return this.ltsMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.ltsMenuField, value) != true)) {
                    this.ltsMenuField = value;
                    this.RaisePropertyChanged("ltsMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ltsPayment {
            get {
                return this.ltsPaymentField;
            }
            set {
                if ((object.ReferenceEquals(this.ltsPaymentField, value) != true)) {
                    this.ltsPaymentField = value;
                    this.RaisePropertyChanged("ltsPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ltsServicesCharges {
            get {
                return this.ltsServicesChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.ltsServicesChargesField, value) != true)) {
                    this.ltsServicesChargesField = value;
                    this.RaisePropertyChanged("ltsServicesCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ltsTender {
            get {
                return this.ltsTenderField;
            }
            set {
                if ((object.ReferenceEquals(this.ltsTenderField, value) != true)) {
                    this.ltsTenderField = value;
                    this.RaisePropertyChanged("ltsTender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreArchivoField, value) != true)) {
                    this.nombreArchivoField = value;
                    this.RaisePropertyChanged("nombreArchivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMicros")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogMicros.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarLog", ReplyAction="http://tempuri.org/IService1/InsertarLogResponse")]
        void InsertarLog(string claveFacto, string centroConsumo, string nombreFile, string errorTry, string error, System.DateTime recordDate, string referencia_CI_CC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertarTrama", ReplyAction="http://tempuri.org/IService1/InsertarTramaResponse")]
        void InsertarTrama(string claveFacto, string centroConsumo, string nombreFile, ServiceTramasMicros.LogMicros.EnviarLogTrama trama, System.DateTime recordDate, string referencia_CI_CC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServiceTramasMicros.LogMicros.CompositeType GetDataUsingDataContract(ServiceTramasMicros.LogMicros.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ServiceTramasMicros.LogMicros.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceTramasMicros.LogMicros.IService1>, ServiceTramasMicros.LogMicros.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public void InsertarLog(string claveFacto, string centroConsumo, string nombreFile, string errorTry, string error, System.DateTime recordDate, string referencia_CI_CC) {
            base.Channel.InsertarLog(claveFacto, centroConsumo, nombreFile, errorTry, error, recordDate, referencia_CI_CC);
        }
        
        public void InsertarTrama(string claveFacto, string centroConsumo, string nombreFile, ServiceTramasMicros.LogMicros.EnviarLogTrama trama, System.DateTime recordDate, string referencia_CI_CC) {
            base.Channel.InsertarTrama(claveFacto, centroConsumo, nombreFile, trama, recordDate, referencia_CI_CC);
        }
        
        public ServiceTramasMicros.LogMicros.CompositeType GetDataUsingDataContract(ServiceTramasMicros.LogMicros.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
